# ========= Build =========
FROM ghcr.io/graalvm/jdk-community:21 AS build

# 安装 native-image 和 gradlew 需要的工具
RUN microdnf install -y findutils tar gzip unzip \
    && gu install native-image

WORKDIR /workspace

COPY . .

RUN chmod +x gradlew

RUN ./gradlew :backend:admin:nativeCompile --no-daemon

# ========= Runtime =========
FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build \
    /workspace/backend/admin/build/native/nativeCompile/admin \
    ./admin

EXPOSE 8080

ENTRYPOINT ["./admin"]