rootProject.name = "app-native"

include("backend")
include("backend:admin")
include("backend:components")
include("backend:components:api-component")
include("backend:components:bean-component")
include("backend:components:core-component")
include("backend:components:domain-component")
include("backend:components:excel-component")
include("backend:components:i18n-component")
include("backend:components:json-component")
include("backend:components:rest-component")
include("backend:components:rest-component:rest-annotation-component")
include("backend:components:rest-component:rest-apt-component")
include("backend:components:security-component")
include("backend:components:storage-component")
include("backend:components:tenant-component")

include("backend:components:storage-component:api-storage-component")
include("backend:components:lock-component")
include("backend:components:lock-component:api-lock-component")
include("backend:components:lock-component:simple-lock-component")
include("backend:components:lock-component:database-lock-component")
include("backend:components:lock-component:redis-lock-component")