rootProject.name = "app-native"

include("backend")
include("backend:admin")
include("backend:components")
include("backend:components:api-component")
include("backend:components:bean-component")
include("backend:components:core-component")
include("backend:components:domain-component")
include("backend:components:excel-component")
include("backend:components:i18n-component")
include("backend:components:json-component")
include("backend:components:rest-component")
include("backend:components:rest-component:rest-annotation-component")
include("backend:components:rest-component:rest-apt-component")
include("backend:components:security-component")
include("backend:components:storage-component")
include("backend:components:tenant-component")

include("backend:components:storage-component:api-storage-component")
include("backend:components:storage-component:redisson-storage-component")
include("backend:components:storage-component:spring-cache-storage-component")
include("backend:components:storage-component:jetcache-storage-component")
include("backend:components:lock-component")
include("backend:components:lock-component:api-lock-component")
include("backend:components:lock-component:simple-lock-component")
include("backend:components:lock-component:database-lock-component")
include("backend:components:lock-component:redis-lock-component")
include("backend:components:security-component:api-security-component")
include("backend:components:security-component:core-security-component")
include("backend:components:security-component:jwt-auth-security-component")
include("backend:components:tenant-component:api-tenant-component")
include("backend:components:security-component:cookie-auth-security-component")
include("backend:components:security-component:captcha-auth-security-component")
include("backend:components:sms-component")
include("backend:components:captcha-component")


include("backend:components:doc-component")
include("backend:components:oss-component")
include("backend:components:oss-component:api-oss-component")
include("backend:components:oss-component:core-oss-component")
include("backend:components:oss-component:jpa-oss-component")
include("backend:components:oss-component:jdbc-oss-component")
include("backend:components:log-component")
include("backend:components:log-component:api-log-component")
include("backend:components:log-component:core-log-component")
include("backend:components:log-component:jpa-log-component")
include("backend:components:message-component")
include("backend:components:message-component:api-message-component")
include("backend:components:message-component:redis-message-component")
include("backend:components:message-component:rabbit-message-component")
include("backend:components:message-component:kafka-message-component")
include("backend:components:log-component:message-log-component")
include("backend:components:form-schema-component")


dependencyResolutionManagement {
    repositories {
//        maven {
//            url = uri("http://192.168.56.106:8081/repository/maven-public/")
//            isAllowInsecureProtocol = true
//        }

        mavenCentral()
    }
}
include("backend:components:camunda-component")
include("backend:components:camunda-component:api-camunda-component")
include("backend:components:camunda-component:jpa-camunda-component")
include("backend:components:camunda-component:remote-camunda-component")
include("backend:components:camunda-component:api-engine-component")
include("backend:components:camunda-component:embedded-engine-component")
include("backend:components:camunda-component:remote-engine-component")
include("backend:components:config-component")
include("backend:components:config-component:api-config-component")
include("backend:components:config-component:client-config-component")
include("backend:components:config-component:server-config-component")
include("backend:workflow")
include("backend:module")
include("backend:module:workflow-module")
include("backend:components:security-component:rbac-security-component")
include("backend:components:security-component:abac-security-component")
include("backend:components:security-component:rbac-security-component:rbac-serve-security-component")
include("backend:components:security-component:rbac-security-component:rbac-client-security-component")