spring:
  # JPA / Hibernate 配置
  datasource:
    url: jdbc:h2:file:./data/admin_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # 开发环境自动建表（含流程表 wf_workflow / wf_workflow_version）
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 4

  # 开启 H2 控制台（可选），方便在浏览器查看数据库
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  info:
    title: zengAlt
    description: workflow接口文档
    version: 1.0.0

    contact:
      name: zengAlt
      email: admin@example.com
      url: https://example.com

security:
  jwt-auth:
    base64-secret: "aGRzaGRnYWhkampydXV1dWtkZGRkamZzc2ZqamlrZHNzZGdkZ2RzamdrLGIvY24yNTQ0Ly4tPT1bXTIzOTQ0NzUwLWpmZHNzZ2htdGtqanR0dGV0NGJhZGFocG9laW9uYmlqcGRpYW9oamo0MzA4MDUzMGhnanl5aW9wc29vcGRvZmZqbm1rbW1tbWdoMFtbWzQ4M3FodTMyMm9yNjY0NDY0OHd3YWhzandiYWRoYWhkYWFhYWZlcmhhd2VlYzNmZGpzZGRzaA=="
    base64-secret-refresh: "c1cyMmxvbmdoYXc1cyMmxvbmdoYXNoNTEyc2VjcmV0a2V5dGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hc1cyMmxvbmdoYXc1cyMmxvbmdoYXNoNTEyc2VjcmV0a2V5c1cyMmxvbmdoYXc1cyMmxvbmdoYXNoNTEyc2VjcmV0a2V5dGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hbmRpdHdvcmtzZdGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hbmRpdHdvcmtzZbmRpdHdvcmtzZm9yaHNpZ25hdHVyZXlvdXRoZWxwYmFzZTY0ZW5jb2RlZGFuZHN0dWZmbGlrZXlvdXJ0ZXh0dGhhdHNob3VsZGJlZWNoNTEyc2VjcmV0a2V5dGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hbmRpdHdvcmtzZm9yaHNpZ25hdHVyZXlvdXRoZWxwYmFzZTY0ZW5jb2RlZGFuZHN0dWZmbGlrZXlvdXJ0ZXh0dGhhdHNob3VsZGJlZW5vdXRoZXJ0Zg=="
    validation: true
  context:
    enabled-access: true


camunda:
  bpm:
    authorization:
      enabled: false
      tenant-check-enabled: false
    job-execution:
      enabled: true
      deployment-aware: true
      core-pool-size: 4
      max-pool-size: 10
      queue-capacity: 3

alt:
  camunda:
    identity:
      admin:
        enabled: true
        base-url: http://127.0.0.1:8080