spring:
  application:
    name: admin-application
  profiles:
    active: 

logging:
  register-shutdown-hook: false

# i18n configuration (default: file mode)
alt:
  i18n:
    mode: file
    basename: messages
    prefix: /api/i18n-messages
