server:
  port: 8080

spring:
  application:
    name: admin-application
  profiles:
    active: dev

logging:
  register-shutdown-hook: false

# i18n configuration (default: file mode)
#alt:
#  i18n:
#    mode: database
#    basename: messages
#    prefix: /api/i18n-messages
