spring:
  # 开启 Docker Compose 自动管理
  docker:
    compose:
      enabled: false
      file: backend/admin/compose.yaml
      # 配置远程虚拟机的 Docker 地址 (请将 192.168.x.x 替换为你虚拟机的实际 IP)
      host: tcp://192.168.56.106:2375
      # 可选: 设置生命周期，比如应用停止时不要停止容器（如果你希望它们一直运行）
      # lifecycle-management: start-only
  
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # JPA / Hibernate 配置
  datasource:
    url: jdbc:h2:mem:admin_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none # 因为使用了 Liquibase，所以将其设为 validate（或 none）以防止 Hibernate 自动修改表结构
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 4

#  cache:
#    type: caffeine
#    caffeine:
#      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=24h,expireAfterAccess=2h,recordStats

  # 开启 H2 控制台（可选），方便在浏览器查看数据库
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    parameters:
      tenantName: master

# 国际化-数据库模式配置（取消注释以启用数据库模式）
# alt:
#   i18n:
#     mode: database


security:
  jwt-auth:
    base64-secret: "aGRzaGRnYWhkampydXV1dWtkZGRkamZzc2ZqamlrZHNzZGdkZ2RzamdrLGIvY24yNTQ0Ly4tPT1bXTIzOTQ0NzUwLWpmZHNzZ2htdGtqanR0dGV0NGJhZGFocG9laW9uYmlqcGRpYW9oamo0MzA4MDUzMGhnanl5aW9wc29vcGRvZmZqbm1rbW1tbWdoMFtbWzQ4M3FodTMyMm9yNjY0NDY0OHd3YWhzandiYWRoYWhkYWFhYWZlcmhhd2VlYzNmZGpzZGRzaA=="
    base64-secret-refresh: "c1cyMmxvbmdoYXc1cyMmxvbmdoYXNoNTEyc2VjcmV0a2V5dGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hc1cyMmxvbmdoYXc1cyMmxvbmdoYXNoNTEyc2VjcmV0a2V5c1cyMmxvbmdoYXc1cyMmxvbmdoYXNoNTEyc2VjcmV0a2V5dGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hbmRpdHdvcmtzZdGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hbmRpdHdvcmtzZbmRpdHdvcmtzZm9yaHNpZ25hdHVyZXlvdXRoZWxwYmFzZTY0ZW5jb2RlZGFuZHN0dWZmbGlrZXlvdXJ0ZXh0dGhhdHNob3VsZGJlZWNoNTEyc2VjcmV0a2V5dGhhdGlzNjRicnl0ZXNmb3J0aGVuZXdyZWZyZXNodG9rZW5hbmRpdHdvcmtzZm9yaHNpZ25hdHVyZXlvdXRoZWxwYmFzZTY0ZW5jb2RlZGFuZHN0dWZmbGlrZXlvdXJ0ZXh0dGhhdHNob3VsZGJlZW5vdXRoZXJ0Zg=="
    authentication: true
    validation: true
    login:
      loginPath: "/v1/login/jwt"
    logout:
      logoutPath: "/v1/logout/jwt"
  username-login:
    enabled: true
  captcha-auth:
    validation: true
    login-path: /v1/login/**

  filter:
    ignore-url:
      - "/v1/auth/captcha"
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/webjars/**"
  context:
    enabled-access: true
    admin:
      id: 1
      code: admin
  rbac:
    client:
      enabled: true


springdoc:
  info:
    title: zengAlt
    description: app--native接口文档
    version: 1.0.0

    contact:
      name: zengAlt
      email: admin@example.com
      url: https://example.com

    license:
      name: Apache License 2.0
      identifier: Apache-2.0
      # 或者使用 url（二选一）
      # url: https://www.apache.org/licenses/LICENSE-2.0.html

  external-docs:
    description: 开发文档
    url: https://example.com/docs

  servers:
    - url: http://localhost:8080
      description: 本地环境

    - url: https://api.example.com
      description: 生产环境

  tags:

    - name: 系统管理
      description: 系统管理接口

  components:

    security-schemes:

      bearerAuth:
        type: http
        scheme: bearer
        bearer-format: JWT
        description: JWT Bearer Token
#      session:
#        type: apiKey
#        in: cookie
#        name: JSESSIONID
#        description: Session Cookie

oss:
  s3:
    enabled: true
    endpoint: file:///d:/data/oss
    storageType: file

  thumbnail:
    enabled: true