--liquibase formatted sql

--changeset zengJiaJun:1
CREATE TABLE sys_oss_file (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    original_file_name VARCHAR(255),
    file_suffix VARCHAR(50),
    file_size BIGINT,
    content_type VARCHAR(127),
    bucket_name VARCHAR(255),
    etag VARCHAR(255),
    md5 VARCHAR(32),
    url VARCHAR(2048),
    storage_type VARCHAR(50) DEFAULT 's3',
    status TINYINT DEFAULT 0,
    tenant_id VARCHAR(50),
    created_by VARCHAR(50),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP,
    CONSTRAINT pk_sys_oss_file PRIMARY KEY (file_id)
);
