--liquibase formatted sql

--changeset zeng:init-log-tables
CREATE TABLE sys_oper_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        VARCHAR(255),
    title            VARCHAR(255),
    business_type    INTEGER,
    method           VARCHAR(255),
    request_method   VARCHAR(255),
    operator_type    INTEGER,
    oper_name        VARCHAR(255),
    dept_name        VARCHAR(255),
    oper_url         VARCHAR(255),
    oper_ip          VARCHAR(128),
    oper_location    VARCHAR(255),
    oper_param       TEXT,
    json_result      TEXT,
    status           INTEGER,
    error_msg        TEXT,
    oper_time        TIMESTAMP,
    cost_time        BIGINT
);

CREATE TABLE sys_logininfor (
    id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        VARCHAR(255),
    username         VARCHAR(255),
    ip               VARCHAR(128),
    status           VARCHAR(255),
    message          TEXT,
    login_time       TIMESTAMP
);

CREATE INDEX idx_sys_oper_log_oper_time   ON sys_oper_log(oper_time);
CREATE INDEX idx_sys_oper_log_oper_name   ON sys_oper_log(oper_name);
CREATE INDEX idx_sys_logininfor_login_time ON sys_logininfor(login_time);
CREATE INDEX idx_sys_logininfor_username  ON sys_logininfor(username);
