services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: admin-postgres
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: admin-redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: